# Generated by Django 5.1.2 on 2024-10-21 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_agent",
                    models.CharField(
                        choices=[
                            ("Индивидуальный предприниматель", "ip"),
                            ("Розничная сеть", "retail"),
                            ("Завод", "factory"),
                        ],
                        verbose_name="Тип контрагента",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя контрагента"),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Электронная почта"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(max_length=100, verbose_name="Номер дома"),
                ),
                (
                    "duty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Задолженность",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Уровень в сети"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название продукта"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="Название модели"),
                ),
                (
                    "date_launch_market",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания звена"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_link",
                        to="main.agent",
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_link",
                        to="main.agent",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено",
                "verbose_name_plural": "Звенья",
            },
        ),
    ]
