# Generated by Django 5.1.2 on 2024-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="duty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=20,
                null=True,
                verbose_name="Задолженность",
            ),
        ),
    ]
