# Generated by Django 5.1.2 on 2024-11-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_agent_duty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="duty",
        ),
        migrations.AddField(
            model_name="link",
            name="duty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=20,
                null=True,
                verbose_name="Задолженность",
            ),
        ),
    ]
